### ISSUE TITLE
ShopifyApiClient blows up when activating a charge

### ISSUE THREAD

**Issue by barranger** [cmcdonaldca/shopify.net#1]
according to the docs here: http://api.shopify.com/applicationcharge.html#activate

The application charge activate endpoint doesn't return any json and as such a Error reading JObject from JsonReader. Path '', line 1, position 1. JsonReaderException is thrown because it's trying to parse an empty string.

**Comment by cmcdonaldca** [comment]
Thanks Barranger, feel free to fix it in your branch and send over a pull request.  It could be a little while before I get a chance to fix this.

**Comment by barranger** [comment]
Working on it right now :)

are you ok with me returning null if the response is an empty string?

**Comment by cmcdonaldca** [comment]
makes sense to me
